"""empty message

Revision ID: 5da51ce11db8
Revises: 5c982348d190
Create Date: 2024-03-14 21:54:27.750675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5da51ce11db8'
down_revision = '5c982348d190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('OTPkey', sa.String(), nullable=False))
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_column('uri')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uri', sa.VARCHAR(), nullable=False))
        batch_op.alter_column('date_of_birth',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.drop_column('OTPkey')

    # ### end Alembic commands ###
