"""empty message

Revision ID: 9c7669dfb97d
Revises: 08ec256a2c81
Create Date: 2024-03-12 15:57:27.809310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c7669dfb97d'
down_revision = '08ec256a2c81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_token', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('persistent_token', sa.String(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_bank_table_link_token'), ['link_token'])
        batch_op.create_unique_constraint(batch_op.f('uq_bank_table_persistent_token'), ['persistent_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_bank_table_persistent_token'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_bank_table_link_token'), type_='unique')
        batch_op.drop_column('persistent_token')
        batch_op.drop_column('link_token')

    # ### end Alembic commands ###
